#!/usr/bin/env python3
"""Regenerate the Packages table in README.md from the bucket's manifests.

Scans ``bucket/*.json`` and classifies each manifest into an install route from
its own fields (``checkver``/``depends``/``installer``), then rewrites the table
between the ``BEGIN/END PACKAGES TABLE`` markers in README.md. Everything shown
is derived from the manifest, so the table can never drift from what ships.

Three routes, mirroring the tap's cask/formula split:

- **binary** — a GitHub-Releases ``.zip`` shimmed as an ``.exe`` (``checkver.github``,
  a ``bin``); no Python required. The *cask* analogue.
- **pipx shim** — ``"depends": "pipx"``; ``pipx install`` from PyPI, needs Python.
- **uv-tool shim** — ``"depends": "uv"``; ``uv tool install`` from PyPI. uv fetches
  its own Python, so nothing else is needed (the ``No`` carries a ``¹`` footnote
  that lives outside the markers).

Standard library only. Run with no arguments to rewrite README.md in place, or
with ``--check`` to fail (non-zero exit) when the table is stale — used in CI so
adding a manifest without regenerating the table is caught in review.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = REPO / "README.md"
BUCKET = REPO / "bucket"

BEGIN = "<!-- BEGIN PACKAGES TABLE (generated by scripts/gen_readme_packages.py — do not edit by hand) -->"
END = "<!-- END PACKAGES TABLE -->"

# Trailing route hint appended to a manifest's description, stripped for display.
_SUFFIX = re.compile(r"\s*\((?:uv tool install|pipx install)\)\s*$")
# Package name installed by a shim, e.g. "keycast" from "pipx install keycast==1.0".
_PKG = re.compile(r"(?:uv tool install|pipx install)\s+([A-Za-z0-9._-]+)")

# route key -> (label, source, needs-Python) columns.
_ROUTE = {
    "binary": ("binary", "GitHub Releases", "No"),
    "pipx": ("pipx shim", "PyPI", "Yes (3.14+)"),
    "uv": ("uv-tool shim", "PyPI", "No¹"),
}
# Stable display order: binary, then pipx, then uv; alphabetical within a route.
_ORDER = {"binary": 0, "pipx": 1, "uv": 2}


def cell(value: str) -> str:
    """Make a string safe for a Markdown table cell.

    Manifest descriptions come from lightly-normalized PyPI summaries, so a raw
    ``|`` would open a spurious column and an embedded newline would split the
    row. Collapse whitespace (incl. newlines) and escape pipes.
    """
    return " ".join(value.split()).replace("|", "\\|")


def route(manifest: dict) -> str:
    """Classify a manifest into ``binary``/``pipx``/``uv`` from its fields."""
    depends = manifest.get("depends")
    if depends == "pipx":
        return "pipx"
    if depends == "uv":
        return "uv"
    return "binary"


def pypi_name(manifest: dict, stem: str) -> str:
    """PyPI package a shim installs (``keycast`` for ``keycast-pipx``), or the stem."""
    script = (manifest.get("installer") or {}).get("script", "")
    match = _PKG.search(script)
    return match.group(1) if match else stem


def links(manifest: dict, kind: str, pkg: str) -> str:
    """Render the ``([repo] · [PyPI])`` link suffix for the description cell."""
    homepage = manifest.get("homepage", "")
    parts = []
    if homepage:
        parts.append(f"[repo]({homepage})")
    if kind != "binary":
        parts.append(f"[PyPI](https://pypi.org/project/{pkg}/)")
    return f" ({' · '.join(parts)})" if parts else ""


def build_table() -> str:
    """Render the Markdown packages table (marker comments included)."""
    rows = ["| Package | What it does | Route | Needs Python? | Source |",
            "|---|---|---|---|---|"]
    manifests = []
    for path in BUCKET.glob("*.json"):
        manifest = json.loads(path.read_text())
        manifests.append((path.stem, manifest, route(manifest)))
    manifests.sort(key=lambda item: (_ORDER[item[2]], item[0]))

    for stem, manifest, kind in manifests:
        label, source, python = _ROUTE[kind]
        desc = cell(_SUFFIX.sub("", manifest.get("description", "")))
        pkg = pypi_name(manifest, stem)
        rows.append(
            f"| `{stem}` | {desc}{links(manifest, kind, pkg)} "
            f"| {label} | {python} | {source} |"
        )
    return "\n".join([BEGIN, *rows, END])


def splice(readme: str, table: str) -> str:
    """Replace the marked region of the README with a freshly built table."""
    start, end = readme.find(BEGIN), readme.find(END)
    if start == -1 or end == -1:
        sys.exit("error: BEGIN/END PACKAGES TABLE markers not found in README.md")
    return readme[:start] + table + readme[end + len(END):]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if README.md is out of date")
    args = parser.parse_args()

    current = README.read_text()
    updated = splice(current, build_table())

    if args.check:
        if current != updated:
            sys.exit("README.md packages table is stale; run "
                     "`python scripts/gen_readme_packages.py`")
        print("README.md packages table is up to date")
        return

    if current != updated:
        README.write_text(updated)
        print("Updated README.md packages table")
    else:
        print("README.md packages table already up to date")


if __name__ == "__main__":
    main()
